# Generated by Django 5.2.1 on 2025-05-14 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('usuario', models.CharField(max_length=255, verbose_name='usuario')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email')),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('date_joined', models.DateTimeField(default=10800)),
                ('genero', models.CharField(choices=[('HOMEN', 'Homen'), ('MULHER', 'Mulher'), ('NAO_BINARIO', 'Não-binario'), ('SEM_RESPOSTA', 'sem/resposta')], max_length=20, verbose_name='genero')),
                ('nome', models.CharField(max_length=50, verbose_name='nome')),
                ('cpf', models.CharField(max_length=10, verbose_name='CPF')),
                ('data_de_nascimento', models.DateField()),
                ('pais', models.CharField(max_length=50, verbose_name='PAIS')),
                ('cidade', models.CharField(max_length=50, verbose_name='CIDADE')),
                ('cep', models.CharField(max_length=30, verbose_name='CEP')),
                ('endereco', models.CharField(max_length=60, verbose_name='Endereço')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
