# Generated by Django 5.2.1 on 2025-05-16 08:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('carrinho', '0001_initial'),
        ('categoria', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('nome', models.CharField(max_length=50, verbose_name='nome')),
                ('descricao', models.TextField(verbose_name='')),
                ('img', models.ImageField(upload_to=None, verbose_name='imagen')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estoque', models.IntegerField()),
                ('categoria', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='categoria.categoria')),
                ('produto_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carrinho.carrinho')),
            ],
        ),
    ]
